import pygame
import math
from pathlib import Path

pygame.init()

class Globals:
    BASEWIDTH = 500
    BASEHEIGHT = 250
    FPS = 60
    TILESIZE = 16
    SCALE = 2
    SCREENWIDTH = BASEWIDTH * SCALE
    SCREENHEIGHT = BASEHEIGHT * SCALE

BASEWIDTH = Globals.BASEWIDTH
BASEHEIGHT = Globals.BASEHEIGHT
SCREENWIDTH = Globals.SCREENWIDTH
SCREENHEIGHT = Globals.SCREENHEIGHT
FPS = Globals.FPS
TILESIZE = Globals.TILESIZE
SCALE = Globals.SCALE

